/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.itfox.beans;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author belchiorpalma
 */
public class Table {
    private String filename;
    private String tablename;
    private String fields;
    private String fieldsOnDuplicate;
    private final List<Table> listTable = new ArrayList<Table>();

   
    public Table(){}
    
    public List<Table> listTable(){
        listTable.add(new Table("areaoper","AREAOPER","(AREA_OPERACIONAL,DESCRICAO)"));
        listTable.add(new Table("combustivel","COMBUSTIVEL","(COMBUSTIVEL,DESCRICAO)"));
        listTable.add(new Table("concessionarios","CONCESSIONARIOS","(CODIGO,NOME, GRUPO_ECONOMICO, CONTA_MBB, MUNICIPIO_SEDE, ZM, CELULAR)"));
        listTable.add(new Table("distrassob","DISTRASSOB","(DISTRITO_ASSOBENS,DESCRICAO)"));
        listTable.add(new Table("emplacamentos","EMPLACAMENTOS","(DATA, CHASSI, PLACA, MODELO, POTENCIA, CAPAC_CARGA, CAPAC_PASSAGEIRO, ANO_FABRIC, COMBUSTIVEL, FABRICANTE, MUNICIPIO, RAZAO_SOCIAL, CNPJ)"));
        listTable.add(new Table("grupomunic","GRUPOMUNIC","(CONCESSIONARIO, GRUPO, DESCRICAO, SEQUENCIA)"));
        listTable.add(new Table("marcas","MARCAS","(MARCA,DESCRICAO)"));
        listTable.add(new Table("modelos","MODELOS","(MODELO, DESCRICAO, FABRICANTE, SEGMENTO, SUBSEGMENTO, NACIONALIDADE, REFERENCIA, TIPO_TERRENO)"));
        listTable.add(new Table("municipios","MUNICIPIOS","(MUNICIPIO, NOME, AREA_OPERACIONAL, REGIAO_MBB, DISTRITO_ASSOBENS, REGIAO_GEOGRAFICA, ESTADO )"));
        listTable.add(new Table("regiaogeogr","REGIAOGEOGR","(REGIAO_GEOGRAFICA,DESCRICAO)"));
        listTable.add(new Table("regiaomb","REGIAOMB","(REGIAO_MERCEDES_BENZ,DESCRICAO)"));
        listTable.add(new Table("segmento","SEGMENTO","(SEGMENTO,DESCRICAO, REFERENCIA)"));
        listTable.add(new Table("seqareaoper","SEQAREAOPER","(SEQUENCIA,AREA_OPERACIONAL)"));
        listTable.add(new Table("seqmunic","SEQMUNIC","(SEQUENCIA,MUNICIPIO)"));
        listTable.add(new Table("subsegmento","SUBSEGMENTO","(SEGMENTO,SUBSEGMENTO, DESCRICAO, REFERENCIA)"));
        listTable.add(new Table("tipoterreno","TIPOTERRENO","(TIPO_TERRENO,DESCRICAO)"));
        //listTable.add(new Table("pf_retorno", "PF_RETORNO","(PLACA,MUNICIPIO,UF,RENAVAM,SITUACAOVEICULO,ULTIMAATUALIZACAO,CHASSI,REMARCACAOCHASSI,MARCA,ANOFABRICACAO,ANOMODELO,TIPOVEICULO,COR,ESPECIE,CATEGORIA,COMBUSTIVEL,CAPC_CARGA,PROCEDENCIA,CAPC_PASSAGEIROS,MOTOR,TIPOMONTAGEM,CARROCERIA,POTENCIA,CILINDRADA,CAIXA_CAMBIO,NUM_CARROCERIA,CAP_MAX_TRACAO,AGENTEFINANCEIRO,NOMEPROPRIETARIO,TIPOCNPJPROPRIETARIO,CPFCNPJPROPRIETARIO,NOME,SG_SEXO,DT_NASC,ESTADO_CIVIL,NO_MAE,TP_LOGR,NO_LOGR,NU_LOGR,NO_COMPL,NO_BAIRRO,NO_CIDADE,SG_ESTADO,NU_CEP,DDD,TELEFONE,DDD1,TELEFONE1,DDD2,TELEFONE2,DDD3,TELEFONE3,DDD4,TELEFONE4,DDD5,TELEFONE5,DDD_CELULAR1,CELULAR1,DDD_CELULAR2,CELULAR2,DDD_CELULAR3,CELULAR3,DDD_CELULAR4,CELULAR4,EMAIL,QTD_OCORRENCIA_CCF,SITUACAO,IDADE,SIGNO,CNPJ_PART_SOC,CARGO_PART_SOC,DT_ENTRADA_PART_SOC,NU_PART_SOC,DATA_OBITO,FLAG_OBITO,PPE,RG,EMISSOR_RG,UF_RG,CODIGO_CBO,CBO,RENDA_MENSAL,RESTRICAO_BANCO,RESTRICAO_AGENCIA,RESTRICAO_MOTIVO,NO_SOBRENOME,BOLSA_FAMILIA)"));
        listTable.add(new Table("pf_retorno", "PF_RETORNO","(@col1, @col2, @col3, @col4, @col5, @col6, @col7, @col8, @col9, @col10, @col11, @col12, @col13, @col14, @col15, @col16, @col17, @col18, @col19, @col20, @col21, @col22, @col23, @col24, @col25, @col26, @col27, @col28, @col29, @col30, @col31, @col32, @col33, @col34, @col35, @col36, @col37, @col38, @col39, @col40, @col41, @col42, @col43, @col44, @col45, @col46, @col47, @col48, @col49, @col50, @col51, @col52, @col53, @col54, @col55, @col56, @col57, @col58, @col59, @col60, @col61, @col62, @col63, @col64, @col65, @col66, @col67, @col68, @col69, @col70, @col71, @col72, @col73, @col74, @col75, @col76, @col77, @col78, @col79, @col80, @col81, @col82, @col83, @col84, @col85, @col86, @col87, @col88) set PLACA=@col1,MUNICIPIO=@col2,UF=@col3,RENAVAM=@col4,SITUACAOVEICULO=@col5,ULTIMAATUALIZACAO=@col6,CHASSI=@col7,REMARCACAOCHASSI=@col8,MARCA=@col9,ANOFABRICACAO=@col10,ANOMODELO=@col11,TIPOVEICULO=@col12,COR=@col13,ESPECIE=@col14,CATEGORIA=@col15,COMBUSTIVEL=@col16,CAPC_CARGA=@col17,PROCEDENCIA=@col18,CAPC_PASSAGEIROS=@col19,MOTOR=@col20,TIPOMONTAGEM=@col21,CARROCERIA=@col22,POTENCIA=@col23,CILINDRADA=@col24,CAIXA_CAMBIO=@col25,NUM_CARROCERIA=@col26,CAP_MAX_TRACAO=@col27,AGENTEFINANCEIRO=@col28,NOMEPROPRIETARIO=@col29,TIPOCNPJPROPRIETARIO=@col30,CPFCNPJPROPRIETARIO=@col31,NOME=@col32,SG_SEXO=@col33,DT_NASC=@col34,ESTADO_CIVIL=@col35,NO_MAE=@col36,TP_LOGR=@col37,NO_LOGR=@col38,NU_LOGR=@col39,NO_COMPL=@col40,NO_BAIRRO=@col41,NO_CIDADE=@col42,SG_ESTADO=@col43,NU_CEP=@col44,DDD=@col45,TELEFONE=@col46,DDD1=@col47,TELEFONE1=@col48,DDD2=@col49,TELEFONE2=@col50,DDD3=@col51,TELEFONE3=@col52,DDD4=@col53,TELEFONE4=@col54,DDD5=@col55,TELEFONE5=@col56,DDD_CELULAR1=@col57,CELULAR1=@col58,DDD_CELULAR2=@col59,CELULAR2=@col60,DDD_CELULAR3=@col61,CELULAR3=@col62,DDD_CELULAR4=@col63,CELULAR4=@col64,EMAIL=@col65,QTD_OCORRENCIA_CCF=@col66,SITUACAO=@col67,IDADE=@col68,SIGNO=@col69,CNPJ_PART_SOC=@col70,CARGO_PART_SOC=@col71,DT_ENTRADA_PART_SOC=@col72,NU_PART_SOC=@col73,DATA_OBITO=@col74,FLAG_OBITO=@col75,PPE=@col76,RG=@col77,EMISSOR_RG=@col78,UF_RG=@col79,CODIGO_CBO=@col80,CBO=@col81,RENDA_MENSAL=@col82,RESTRICAO_BANCO=@col83,RESTRICAO_AGENCIA=@col84,RESTRICAO_MOTIVO=@col85,NO_SOBRENOME=@col86,BOLSA_FAMILIA=@col87 " +
                                                        "","PLACA = VALUES(PLACA), MUNICIPIO = VALUES(MUNICIPIO), UF = VALUES(UF), RENAVAM = VALUES(RENAVAM), SITUACAOVEICULO = VALUES(SITUACAOVEICULO), ULTIMAATUALIZACAO = VALUES(ULTIMAATUALIZACAO), CHASSI = VALUES(CHASSI), REMARCACAOCHASSI = VALUES(REMARCACAOCHASSI), MARCA = VALUES(MARCA), ANOFABRICACAO = VALUES(ANOFABRICACAO), ANOMODELO = VALUES(ANOMODELO), TIPOVEICULO = VALUES(TIPOVEICULO), COR = VALUES(COR), ESPECIE = VALUES(ESPECIE), CATEGORIA = VALUES(CATEGORIA), COMBUSTIVEL = VALUES(COMBUSTIVEL), CAPC_CARGA = VALUES(CAPC_CARGA), PROCEDENCIA = VALUES(PROCEDENCIA), CAPC_PASSAGEIROS = VALUES(CAPC_PASSAGEIROS), MOTOR = VALUES(MOTOR), TIPOMONTAGEM = VALUES(TIPOMONTAGEM), CARROCERIA = VALUES(CARROCERIA), POTENCIA = VALUES(POTENCIA), CILINDRADA = VALUES(CILINDRADA), CAIXA_CAMBIO = VALUES(CAIXA_CAMBIO), NUM_CARROCERIA = VALUES(NUM_CARROCERIA), CAP_MAX_TRACAO = VALUES(CAP_MAX_TRACAO), AGENTEFINANCEIRO = VALUES(AGENTEFINANCEIRO), NOMEPROPRIETARIO = VALUES(NOMEPROPRIETARIO), TIPOCNPJPROPRIETARIO = VALUES(TIPOCNPJPROPRIETARIO), CPFCNPJPROPRIETARIO = VALUES(CPFCNPJPROPRIETARIO), NOME = VALUES(NOME), SG_SEXO = VALUES(SG_SEXO), DT_NASC = VALUES(DT_NASC), ESTADO_CIVIL = VALUES(ESTADO_CIVIL), NO_MAE = VALUES(NO_MAE), TP_LOGR = VALUES(TP_LOGR), NO_LOGR = VALUES(NO_LOGR), NU_LOGR = VALUES(NU_LOGR), NO_COMPL = VALUES(NO_COMPL), NO_BAIRRO = VALUES(NO_BAIRRO), NO_CIDADE = VALUES(NO_CIDADE), SG_ESTADO = VALUES(SG_ESTADO), NU_CEP = VALUES(NU_CEP), DDD = VALUES(DDD), TELEFONE = VALUES(TELEFONE), DDD1 = VALUES(DDD1), TELEFONE1 = VALUES(TELEFONE1), DDD2 = VALUES(DDD2), TELEFONE2 = VALUES(TELEFONE2), DDD3 = VALUES(DDD3), TELEFONE3 = VALUES(TELEFONE3), DDD4 = VALUES(DDD4), TELEFONE4 = VALUES(TELEFONE4), DDD5 = VALUES(DDD5), TELEFONE5 = VALUES(TELEFONE5), DDD_CELULAR1 = VALUES(DDD_CELULAR1), CELULAR1 = VALUES(CELULAR1), DDD_CELULAR2 = VALUES(DDD_CELULAR2), CELULAR2 = VALUES(CELULAR2), DDD_CELULAR3 = VALUES(DDD_CELULAR3), CELULAR3 = VALUES(CELULAR3), DDD_CELULAR4 = VALUES(DDD_CELULAR4), CELULAR4 = VALUES(CELULAR4), EMAIL = VALUES(EMAIL), QTD_OCORRENCIA_CCF = VALUES(QTD_OCORRENCIA_CCF), SITUACAO = VALUES(SITUACAO), IDADE = VALUES(IDADE), SIGNO = VALUES(SIGNO), CNPJ_PART_SOC = VALUES(CNPJ_PART_SOC), CARGO_PART_SOC = VALUES(CARGO_PART_SOC), DT_ENTRADA_PART_SOC = VALUES(DT_ENTRADA_PART_SOC), NU_PART_SOC = VALUES(NU_PART_SOC), DATA_OBITO = VALUES(DATA_OBITO), FLAG_OBITO = VALUES(FLAG_OBITO), PPE = VALUES(PPE), RG = VALUES(RG), EMISSOR_RG = VALUES(EMISSOR_RG), UF_RG = VALUES(UF_RG), CODIGO_CBO = VALUES(CODIGO_CBO), CBO = VALUES(CBO), RENDA_MENSAL = VALUES(RENDA_MENSAL), RESTRICAO_BANCO = VALUES(RESTRICAO_BANCO), RESTRICAO_AGENCIA = VALUES(RESTRICAO_AGENCIA), RESTRICAO_MOTIVO = VALUES(RESTRICAO_MOTIVO), NO_SOBRENOME = VALUES(NO_SOBRENOME), BOLSA_FAMILIA = VALUES(BOLSA_FAMILIA)"));
        //listTable.add(new Table("pj_retorno", "PJ_RETORNO", "(PLACA,MUNICIPIO,UF,RENAVAM,SITUACAOVEICULO,ULTIMAATUALIZACAO,CHASSI,REMARCACAOCHASSI,MARCA,ANOFABRICACAO,ANOMODELO,TIPOVEICULO,COR,ESPECIE,CATEGORIA,COMBUSTIVEL,CAPC_CARGA,PROCEDENCIA,CAPC_PASSAGEIROS,MOTOR,TIPOMONTAGEM,CARROCERIA,POTENCIA,CILINDRADA,CAIXA_CAMBIO,NUM_CARROCERIA,CAP_MAX_TRACAO,AGENTEFINANCEIRO,NOMEPROPRIETARIO,TIPOCNPJPROPRIETARIO,CPFCNPJPROPRIETARIO,RAZAO_SOCIAL,NOME_FANTASIA,DT_ABERTURA,SITUACAO_RECEITA,ATIVIDADE_ECONOMICA_SECUNDARIA,CO_ATIVIDADE_ECONOMICA_SEC,SITE,NO_LOGR,NU_LOGR,NO_COMPL,NO_BAIRRO,NO_CIDADE,SG_ESTADO,NU_CEP,CO_ATIVIDADE_ECONOMICA,CO_NATUREZA_JURIDICA,ATIVIDADE_ECONOMICA,NATUREZA_JURIDICA,DDD1,TELEFONE1,DDD2,TELEFONE2,DDD3,TELEFONE3,DDD4,TELEFONE4,DDD5,TELEFONE5,DDD_CELULAR1,CELULAR1,DDD_CELULAR2,CELULAR2,QTD_OCORRENCIA_CCF,EMAIL_1,EMAIL_2,EMAIL_3,NU_CPF1,NOME_SOCIO_DIRETOR1,CARGO1,EMAIL_SOCIO1,TP_LOGR_CONTATO1,NO_LOGR_CONTATO1,NU_LOGR_CONTATO1,NO_COMPL_CONTATO1,NO_BAIRRO_CONTATO1,NO_CIDADE_CONTATO1,SG_ESTADO_CONTATO1,NU_CEP_CONTATO1,DDD1_FIXO_SOCIO1,TEL1_FIXO_SOCIO1,DDD2_FIXO_SOCIO1,TEL2_FIXO_SOCIO1,DDD3_FIXO_SOCIO1,TEL3_FIXO_SOCIO1,DDD1_CEL_SOCIO1,TEL1_CEL_SOCIO1,DDD2_CEL_SOCIO1,TEL2_CEL_SOCIO1,NU_CPF2,NOME_SOCIO_DIRETOR2,CARGO2,EMAIL_SOCIO2,TP_LOGR_CONTATO2,NO_LOGR_CONTATO2,NU_LOGR_CONTATO2,NO_COMPL_CONTATO2,NO_BAIRRO_CONTATO2,NO_CIDADE_CONTATO2,SG_ESTADO_CONTATO2,NU_CEP_CONTATO2,DDD1_FIXO_SOCIO2,TEL1_FIXO_SOCIO2,DDD2_FIXO_SOCIO2,TEL2_FIXO_SOCIO2,DDD3_FIXO_SOCIO2,TEL3_FIXO_SOCIO2,DDD1_CEL_SOCIO2,TEL1_CEL_SOCIO2,DDD2_CEL_SOCIO2,TEL2_CEL_SOCIO2,NU_CPF3,NOME_SOCIO_DIRETOR3,CARGO3,EMAIL_SOCIO3,TP_LOGR_CONTATO3,NO_LOGR_CONTATO3,NU_LOGR_CONTATO3,NO_COMPL_CONTATO3,NO_BAIRRO_CONTATO3,NO_CIDADE_CONTATO3,SG_ESTADO_CONTATO3,NU_CEP_CONTATO3,DDD1_FIXO_SOCIO3,TEL1_FIXO_SOCIO3,DDD2_FIXO_SOCIO3,TEL2_FIXO_SOCIO3,DDD3_FIXO_SOCIO3,TEL3_FIXO_SOCIO3,DDD1_CEL_SOCIO3,TEL1_CEL_SOCIO3,DDD2_CEL_SOCIO3,TEL2_CEL_SOCIO3,SG_SEXO_SOCIO1,SG_SEXO_SOCIO2,SG_SEXO_SOCIO3,DT_NASC_SOCIO1,DT_NASC_SOCIO2,DT_NASC_SOCIO3,CNPJ_QSA1,DT_ENTRADA_SOC1,NU_PART_CAP_SOCIAL1,CNPJ_QSA2,DT_ENTRADA_SOC2,NU_PART_CAP_SOCIAL2,CNPJ_QSA3,DT_ENTRADA_SOC3,NU_PART_CAP_SOCIAL3,RESTRICAO_BANCO,RESTRICAO_AGENCIA,RESTRICAO_MOTIVO,EMAIL,NU_CPF_CNPJ1,NU_CPF_CNPJ2,NU_CPF_CNPJ3)"));
        listTable.add(new Table("pj_retorno", "PJ_RETORNO","(@col1, @col2, @col3, @col4, @col5, @col6, @col7, @col8, @col9, @col10, @col11, @col12, @col13, @col14, @col15, @col16, @col17, @col18, @col19, @col20, @col21, @col22, @col23, @col24, @col25, @col26, @col27, @col28, @col29, @col30, @col31, @col32, @col33, @col34, @col35, @col36, @col37, @col38, @col39, @col40, @col41, @col42, @col43, @col44, @col45, @col46, @col47, @col48, @col49, @col50, @col51, @col52, @col53, @col54, @col55, @col56, @col57, @col58, @col59, @col60, @col61, @col62, @col63, @col64, @col65, @col66, @col67, @col68, @col69, @col70, @col71, @col72, @col73, @col74, @col75, @col76, @col77, @col78, @col79, @col80, @col81, @col82, @col83, @col84, @col85, @col86, @col87, @col88, @col89, @col90, @col91, @col92, @col93, @col94, @col95, @col96, @col97, @col98, @col99, @col100, @col101, @col102, @col103, @col104, @col105, @col106, @col107, @col108, @col109, @col110, @col111, @col112, @col113, @col114, @col115, @col116, @col117, @col118, @col119, @col120, @col121, @col122, @col123, @col124, @col125, @col126, @col127, @col128, @col129, @col130, @col131, @col132, @col133, @col134, @col135, @col136, @col137, @col138, @col139, @col140, @col141, @col142, @col143, @col144, @col145, @col146, @col147, @col148, @col149, @col150, @col151, @col152, @col153, @col154, @col155, @col156) set PLACA=@col1,MUNICIPIO=@col2,UF=@col3,RENAVAM=@col4,SITUACAOVEICULO=@col5,ULTIMAATUALIZACAO=@col6,CHASSI=@col7,REMARCACAOCHASSI=@col8,MARCA=@col9,ANOFABRICACAO=@col10,ANOMODELO=@col11,TIPOVEICULO=@col12,COR=@col13,ESPECIE=@col14,CATEGORIA=@col15,COMBUSTIVEL=@col16,CAPC_CARGA=@col17,PROCEDENCIA=@col18,CAPC_PASSAGEIROS=@col19,MOTOR=@col20,TIPOMONTAGEM=@col21,CARROCERIA=@col22,POTENCIA=@col23,CILINDRADA=@col24,CAIXA_CAMBIO=@col25,NUM_CARROCERIA=@col26,CAP_MAX_TRACAO=@col27,AGENTEFINANCEIRO=@col28,NOMEPROPRIETARIO=@col29,TIPOCNPJPROPRIETARIO=@col30,CPFCNPJPROPRIETARIO=@col31,RAZAO_SOCIAL=@col32,NOME_FANTASIA=@col33,DT_ABERTURA=@col34,SITUACAO_RECEITA=@col35,ATIVIDADE_ECONOMICA_SECUNDARIA=@col36,CO_ATIVIDADE_ECONOMICA_SEC=@col37,SITE=@col38,NO_LOGR=@col39,NU_LOGR=@col40,NO_COMPL=@col41,NO_BAIRRO=@col42,NO_CIDADE=@col43,SG_ESTADO=@col44,NU_CEP=@col45,CO_ATIVIDADE_ECONOMICA=@col46,CO_NATUREZA_JURIDICA=@col47,ATIVIDADE_ECONOMICA=@col48,NATUREZA_JURIDICA=@col49,DDD1=@col50,TELEFONE1=@col51,DDD2=@col52,TELEFONE2=@col53,DDD3=@col54,TELEFONE3=@col55,DDD4=@col56,TELEFONE4=@col57,DDD5=@col58,TELEFONE5=@col59,DDD_CELULAR1=@col60,CELULAR1=@col61,DDD_CELULAR2=@col62,CELULAR2=@col63,QTD_OCORRENCIA_CCF=@col64,EMAIL_1=@col65,EMAIL_2=@col66,EMAIL_3=@col67,NU_CPF1=@col68,NOME_SOCIO_DIRETOR1=@col69,CARGO1=@col70,EMAIL_SOCIO1=@col71,TP_LOGR_CONTATO1=@col72,NO_LOGR_CONTATO1=@col73,NU_LOGR_CONTATO1=@col74,NO_COMPL_CONTATO1=@col75,NO_BAIRRO_CONTATO1=@col76,NO_CIDADE_CONTATO1=@col77,SG_ESTADO_CONTATO1=@col78,NU_CEP_CONTATO1=@col79,DDD1_FIXO_SOCIO1=@col80,TEL1_FIXO_SOCIO1=@col81,DDD2_FIXO_SOCIO1=@col82,TEL2_FIXO_SOCIO1=@col83,DDD3_FIXO_SOCIO1=@col84,TEL3_FIXO_SOCIO1=@col85,DDD1_CEL_SOCIO1=@col86,TEL1_CEL_SOCIO1=@col87,DDD2_CEL_SOCIO1=@col88,TEL2_CEL_SOCIO1=@col89,NU_CPF2=@col90,NOME_SOCIO_DIRETOR2=@col91,CARGO2=@col92,EMAIL_SOCIO2=@col93,TP_LOGR_CONTATO2=@col94,NO_LOGR_CONTATO2=@col95,NU_LOGR_CONTATO2=@col96,NO_COMPL_CONTATO2=@col97,NO_BAIRRO_CONTATO2=@col98,NO_CIDADE_CONTATO2=@col99,SG_ESTADO_CONTATO2=@col100,NU_CEP_CONTATO2=@col101,DDD1_FIXO_SOCIO2=@col102,TEL1_FIXO_SOCIO2=@col103,DDD2_FIXO_SOCIO2=@col104,TEL2_FIXO_SOCIO2=@col105,DDD3_FIXO_SOCIO2=@col106,TEL3_FIXO_SOCIO2=@col107,DDD1_CEL_SOCIO2=@col108,TEL1_CEL_SOCIO2=@col109,DDD2_CEL_SOCIO2=@col110,TEL2_CEL_SOCIO2=@col111,NU_CPF3=@col112,NOME_SOCIO_DIRETOR3=@col113,CARGO3=@col114,EMAIL_SOCIO3=@col115,TP_LOGR_CONTATO3=@col116,NO_LOGR_CONTATO3=@col117,NU_LOGR_CONTATO3=@col118,NO_COMPL_CONTATO3=@col119,NO_BAIRRO_CONTATO3=@col120,NO_CIDADE_CONTATO3=@col121,SG_ESTADO_CONTATO3=@col122,NU_CEP_CONTATO3=@col123,DDD1_FIXO_SOCIO3=@col124,TEL1_FIXO_SOCIO3=@col125,DDD2_FIXO_SOCIO3=@col126,TEL2_FIXO_SOCIO3=@col127,DDD3_FIXO_SOCIO3=@col128,TEL3_FIXO_SOCIO3=@col129,DDD1_CEL_SOCIO3=@col130,TEL1_CEL_SOCIO3=@col131,DDD2_CEL_SOCIO3=@col132,TEL2_CEL_SOCIO3=@col133,SG_SEXO_SOCIO1=@col134,SG_SEXO_SOCIO2=@col135,SG_SEXO_SOCIO3=@col136,DT_NASC_SOCIO1=@col137,DT_NASC_SOCIO2=@col138,DT_NASC_SOCIO3=@col139,CNPJ_QSA1=@col140,DT_ENTRADA_SOC1=@col141,NU_PART_CAP_SOCIAL1=@col142,CNPJ_QSA2=@col143,DT_ENTRADA_SOC2=@col144,NU_PART_CAP_SOCIAL2=@col145,CNPJ_QSA3=@col146,DT_ENTRADA_SOC3=@col147,NU_PART_CAP_SOCIAL3=@col148,RESTRICAO_BANCO=@col149,RESTRICAO_AGENCIA=@col150,RESTRICAO_MOTIVO=@col151,EMAIL=@col152,NU_CPF_CNPJ1=@col153,NU_CPF_CNPJ2=@col154,NU_CPF_CNPJ3=@col155"+ 
                                                        "", "PLACA = VALUES(PLACA), MUNICIPIO = VALUES(MUNICIPIO), UF = VALUES(UF), RENAVAM = VALUES(RENAVAM), SITUACAOVEICULO = VALUES(SITUACAOVEICULO), ULTIMAATUALIZACAO = VALUES(ULTIMAATUALIZACAO), CHASSI = VALUES(CHASSI), REMARCACAOCHASSI = VALUES(REMARCACAOCHASSI), MARCA = VALUES(MARCA), ANOFABRICACAO = VALUES(ANOFABRICACAO), ANOMODELO = VALUES(ANOMODELO), TIPOVEICULO = VALUES(TIPOVEICULO), COR = VALUES(COR), ESPECIE = VALUES(ESPECIE), CATEGORIA = VALUES(CATEGORIA), COMBUSTIVEL = VALUES(COMBUSTIVEL), CAPC_CARGA = VALUES(CAPC_CARGA), PROCEDENCIA = VALUES(PROCEDENCIA), CAPC_PASSAGEIROS = VALUES(CAPC_PASSAGEIROS), MOTOR = VALUES(MOTOR), TIPOMONTAGEM = VALUES(TIPOMONTAGEM), CARROCERIA = VALUES(CARROCERIA), POTENCIA = VALUES(POTENCIA), CILINDRADA = VALUES(CILINDRADA), CAIXA_CAMBIO = VALUES(CAIXA_CAMBIO), NUM_CARROCERIA = VALUES(NUM_CARROCERIA), CAP_MAX_TRACAO = VALUES(CAP_MAX_TRACAO), AGENTEFINANCEIRO = VALUES(AGENTEFINANCEIRO), NOMEPROPRIETARIO = VALUES(NOMEPROPRIETARIO), TIPOCNPJPROPRIETARIO = VALUES(TIPOCNPJPROPRIETARIO), CPFCNPJPROPRIETARIO = VALUES(CPFCNPJPROPRIETARIO), RAZAO_SOCIAL = VALUES(RAZAO_SOCIAL), NOME_FANTASIA = VALUES(NOME_FANTASIA), DT_ABERTURA = VALUES(DT_ABERTURA), SITUACAO_RECEITA = VALUES(SITUACAO_RECEITA), ATIVIDADE_ECONOMICA_SECUNDARIA = VALUES(ATIVIDADE_ECONOMICA_SECUNDARIA), CO_ATIVIDADE_ECONOMICA_SEC = VALUES(CO_ATIVIDADE_ECONOMICA_SEC), SITE = VALUES(SITE), NO_LOGR = VALUES(NO_LOGR), NU_LOGR = VALUES(NU_LOGR), NO_COMPL = VALUES(NO_COMPL), NO_BAIRRO = VALUES(NO_BAIRRO), NO_CIDADE = VALUES(NO_CIDADE), SG_ESTADO = VALUES(SG_ESTADO), NU_CEP = VALUES(NU_CEP), CO_ATIVIDADE_ECONOMICA = VALUES(CO_ATIVIDADE_ECONOMICA), CO_NATUREZA_JURIDICA = VALUES(CO_NATUREZA_JURIDICA), ATIVIDADE_ECONOMICA = VALUES(ATIVIDADE_ECONOMICA), NATUREZA_JURIDICA = VALUES(NATUREZA_JURIDICA), DDD1 = VALUES(DDD1), TELEFONE1 = VALUES(TELEFONE1), DDD2 = VALUES(DDD2), TELEFONE2 = VALUES(TELEFONE2), DDD3 = VALUES(DDD3), TELEFONE3 = VALUES(TELEFONE3), DDD4 = VALUES(DDD4), TELEFONE4 = VALUES(TELEFONE4), DDD5 = VALUES(DDD5), TELEFONE5 = VALUES(TELEFONE5), DDD_CELULAR1 = VALUES(DDD_CELULAR1), CELULAR1 = VALUES(CELULAR1), DDD_CELULAR2 = VALUES(DDD_CELULAR2), CELULAR2 = VALUES(CELULAR2), QTD_OCORRENCIA_CCF = VALUES(QTD_OCORRENCIA_CCF), EMAIL_1 = VALUES(EMAIL_1), EMAIL_2 = VALUES(EMAIL_2), EMAIL_3 = VALUES(EMAIL_3), NU_CPF1 = VALUES(NU_CPF1), NOME_SOCIO_DIRETOR1 = VALUES(NOME_SOCIO_DIRETOR1), CARGO1 = VALUES(CARGO1), EMAIL_SOCIO1 = VALUES(EMAIL_SOCIO1), TP_LOGR_CONTATO1 = VALUES(TP_LOGR_CONTATO1), NO_LOGR_CONTATO1 = VALUES(NO_LOGR_CONTATO1), NU_LOGR_CONTATO1 = VALUES(NU_LOGR_CONTATO1), NO_COMPL_CONTATO1 = VALUES(NO_COMPL_CONTATO1), NO_BAIRRO_CONTATO1 = VALUES(NO_BAIRRO_CONTATO1), NO_CIDADE_CONTATO1 = VALUES(NO_CIDADE_CONTATO1), SG_ESTADO_CONTATO1 = VALUES(SG_ESTADO_CONTATO1), NU_CEP_CONTATO1 = VALUES(NU_CEP_CONTATO1), DDD1_FIXO_SOCIO1 = VALUES(DDD1_FIXO_SOCIO1), TEL1_FIXO_SOCIO1 = VALUES(TEL1_FIXO_SOCIO1), DDD2_FIXO_SOCIO1 = VALUES(DDD2_FIXO_SOCIO1), TEL2_FIXO_SOCIO1 = VALUES(TEL2_FIXO_SOCIO1), DDD3_FIXO_SOCIO1 = VALUES(DDD3_FIXO_SOCIO1), TEL3_FIXO_SOCIO1 = VALUES(TEL3_FIXO_SOCIO1), DDD1_CEL_SOCIO1 = VALUES(DDD1_CEL_SOCIO1), TEL1_CEL_SOCIO1 = VALUES(TEL1_CEL_SOCIO1), DDD2_CEL_SOCIO1 = VALUES(DDD2_CEL_SOCIO1), TEL2_CEL_SOCIO1 = VALUES(TEL2_CEL_SOCIO1), NU_CPF2 = VALUES(NU_CPF2), NOME_SOCIO_DIRETOR2 = VALUES(NOME_SOCIO_DIRETOR2), CARGO2 = VALUES(CARGO2), EMAIL_SOCIO2 = VALUES(EMAIL_SOCIO2), TP_LOGR_CONTATO2 = VALUES(TP_LOGR_CONTATO2), NO_LOGR_CONTATO2 = VALUES(NO_LOGR_CONTATO2), NU_LOGR_CONTATO2 = VALUES(NU_LOGR_CONTATO2), NO_COMPL_CONTATO2 = VALUES(NO_COMPL_CONTATO2), NO_BAIRRO_CONTATO2 = VALUES(NO_BAIRRO_CONTATO2), NO_CIDADE_CONTATO2 = VALUES(NO_CIDADE_CONTATO2), SG_ESTADO_CONTATO2 = VALUES(SG_ESTADO_CONTATO2), NU_CEP_CONTATO2 = VALUES(NU_CEP_CONTATO2), DDD1_FIXO_SOCIO2 = VALUES(DDD1_FIXO_SOCIO2), TEL1_FIXO_SOCIO2 = VALUES(TEL1_FIXO_SOCIO2), DDD2_FIXO_SOCIO2 = VALUES(DDD2_FIXO_SOCIO2), TEL2_FIXO_SOCIO2 = VALUES(TEL2_FIXO_SOCIO2), DDD3_FIXO_SOCIO2 = VALUES(DDD3_FIXO_SOCIO2), TEL3_FIXO_SOCIO2 = VALUES(TEL3_FIXO_SOCIO2), DDD1_CEL_SOCIO2 = VALUES(DDD1_CEL_SOCIO2), TEL1_CEL_SOCIO2 = VALUES(TEL1_CEL_SOCIO2), DDD2_CEL_SOCIO2 = VALUES(DDD2_CEL_SOCIO2), TEL2_CEL_SOCIO2 = VALUES(TEL2_CEL_SOCIO2), NU_CPF3 = VALUES(NU_CPF3), NOME_SOCIO_DIRETOR3 = VALUES(NOME_SOCIO_DIRETOR3), CARGO3 = VALUES(CARGO3), EMAIL_SOCIO3 = VALUES(EMAIL_SOCIO3), TP_LOGR_CONTATO3 = VALUES(TP_LOGR_CONTATO3), NO_LOGR_CONTATO3 = VALUES(NO_LOGR_CONTATO3), NU_LOGR_CONTATO3 = VALUES(NU_LOGR_CONTATO3), NO_COMPL_CONTATO3 = VALUES(NO_COMPL_CONTATO3), NO_BAIRRO_CONTATO3 = VALUES(NO_BAIRRO_CONTATO3), NO_CIDADE_CONTATO3 = VALUES(NO_CIDADE_CONTATO3), SG_ESTADO_CONTATO3 = VALUES(SG_ESTADO_CONTATO3), NU_CEP_CONTATO3 = VALUES(NU_CEP_CONTATO3), DDD1_FIXO_SOCIO3 = VALUES(DDD1_FIXO_SOCIO3), TEL1_FIXO_SOCIO3 = VALUES(TEL1_FIXO_SOCIO3), DDD2_FIXO_SOCIO3 = VALUES(DDD2_FIXO_SOCIO3), TEL2_FIXO_SOCIO3 = VALUES(TEL2_FIXO_SOCIO3), DDD3_FIXO_SOCIO3 = VALUES(DDD3_FIXO_SOCIO3), TEL3_FIXO_SOCIO3 = VALUES(TEL3_FIXO_SOCIO3), DDD1_CEL_SOCIO3 = VALUES(DDD1_CEL_SOCIO3), TEL1_CEL_SOCIO3 = VALUES(TEL1_CEL_SOCIO3), DDD2_CEL_SOCIO3 = VALUES(DDD2_CEL_SOCIO3), TEL2_CEL_SOCIO3 = VALUES(TEL2_CEL_SOCIO3), SG_SEXO_SOCIO1 = VALUES(SG_SEXO_SOCIO1), SG_SEXO_SOCIO2 = VALUES(SG_SEXO_SOCIO2), SG_SEXO_SOCIO3 = VALUES(SG_SEXO_SOCIO3), DT_NASC_SOCIO1 = VALUES(DT_NASC_SOCIO1), DT_NASC_SOCIO2 = VALUES(DT_NASC_SOCIO2), DT_NASC_SOCIO3 = VALUES(DT_NASC_SOCIO3), CNPJ_QSA1 = VALUES(CNPJ_QSA1), DT_ENTRADA_SOC1 = VALUES(DT_ENTRADA_SOC1), NU_PART_CAP_SOCIAL1 = VALUES(NU_PART_CAP_SOCIAL1), CNPJ_QSA2 = VALUES(CNPJ_QSA2), DT_ENTRADA_SOC2 = VALUES(DT_ENTRADA_SOC2), NU_PART_CAP_SOCIAL2 = VALUES(NU_PART_CAP_SOCIAL2), CNPJ_QSA3 = VALUES(CNPJ_QSA3), DT_ENTRADA_SOC3 = VALUES(DT_ENTRADA_SOC3), NU_PART_CAP_SOCIAL3 = VALUES(NU_PART_CAP_SOCIAL3), RESTRICAO_BANCO = VALUES(RESTRICAO_BANCO), RESTRICAO_AGENCIA = VALUES(RESTRICAO_AGENCIA), RESTRICAO_MOTIVO = VALUES(RESTRICAO_MOTIVO), EMAIL = VALUES(EMAIL), NU_CPF_CNPJ1 = VALUES(NU_CPF_CNPJ1), NU_CPF_CNPJ2 = VALUES(NU_CPF_CNPJ2), NU_CPF_CNPJ3 = VALUES(NU_CPF_CNPJ3)"));
        listTable.add(new Table("chassi","CHASSI","(CHASSI)"));
        return listTable;
    }
    
    public Table(String filename, String tablename, String fields){
        this.filename=filename;
        this.tablename=tablename;
        this.fields=fields;
    }

    public Table(String filename, String tablename, String fields, String fieldsOnDuplicate) {
        this.filename = filename;
        this.tablename = tablename;
        this.fields = fields;
        this.fieldsOnDuplicate = fieldsOnDuplicate;
    }
    

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getTablename() {
        return tablename;
    }

    public void setTablename(String tablename) {
        this.tablename = tablename;
    }

    public String getFields() {
        return fields;
    }

    public void setFields(String fields) {
        this.fields = fields;
    }

    public String getFieldsOnDuplicate() {
        return fieldsOnDuplicate;
    }

    public void setFieldsOnDuplicate(String fieldsOnDuplicate) {
        this.fieldsOnDuplicate = fieldsOnDuplicate;
    }
    
    public Table search(List<Table> listTables, String search){
        Table table = new Table();
        if(listTables!=null && listTable.size()>0){
            for(Table t : listTables){
                // caso vc transfira o arquivo em sua maquina e ele fique com o arquivo-1.txt, ele desconsidera depois do -
                int replacement = search.indexOf("-");//s.substring(0, s.indexOf("(") - 1);
                if(replacement>0){
                    search = search.substring(0,replacement-1);
                }
                if(t.getFilename() != null && t.getFilename().toLowerCase().contains(search.toLowerCase())){
                   //something here
                    return t;
                }
            }
        }
        return table;
    }
    public Table search(String search){
        this.listTable();
        return search(this.listTable,search);
    }
    
}
